<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.java-zengguang</groupId>
    <artifactId>litepress</artifactId>
    <packaging>pom</packaging>
    <version>${revision}</version>

    <name>litePress</name>
    <description>litePress</description>
    <url>https://github.com/java-zengguang/litepress</url>

    <licenses>
        <license>
            <name>MIT License</name>
            <url>https://opensource.org/licenses/MIT</url>
        </license>
    </licenses>

    <scm>
        <url>https://github.com/java-zengguang/litepress</url>
        <connection>scm:git:git://github.com/java-zengguang/litepress.git</connection>
        <developerConnection>scm:git:ssh://git@github.com:java-zengguang/litepress.git</developerConnection>
    </scm>

    <developers>
        <developer>
            <name>曾广</name>
            <email>1573820606@qq.com</email>
        </developer>
    </developers>


    <modules>
        <module>litepress-core</module>
        <module>litepress-web</module>
        <module>litepress-direction</module>
        <module>litepress-cache</module>
        <module>litepress-network</module>
        <module>litepress-chain</module>
        <module>litepress-event</module>
        <module>litepress-task</module>
        <module>litepress-router</module>
        <module>litepress-reaction</module>
        <module>litepress-ml</module>
        <module>litepress-db</module>
        <module>litepress-boot</module>
    </modules>


    <properties>
        <slf4j.api>2.0.13</slf4j.api>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>21</java.version>
        <revision>0.0.1</revision>
    </properties>

    <!-- 发布配置 -->
    <distributionManagement>
        <snapshotRepository>
            <id>central</id>
            <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
        <repository>
            <id>central</id>
            <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
        </repository>
    </distributionManagement>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>commons-collections</groupId>
                <artifactId>commons-collections</artifactId>
                <version>3.2.2</version>
            </dependency>

            <dependency>
                <groupId>org.tinylog</groupId>
                <artifactId>tinylog-api</artifactId>
                <version>2.7.0</version>
            </dependency>
            <dependency>
                <groupId>org.tinylog</groupId>
                <artifactId>tinylog-impl</artifactId>
                <version>2.7.0</version>
            </dependency>

            <!-- https://mvnrepository.com/artifact/io.netty/netty-all -->
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-all</artifactId>
                <version>4.2.2.Final</version>
            </dependency>

            <!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind -->
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>2.19.1</version>
            </dependency>

            <dependency>
                <groupId>org.apache.rocketmq</groupId>
                <artifactId>rocketmq-client</artifactId>
                <version>4.9.8</version>
            </dependency>
            <dependency>
                <groupId>org.apache.rocketmq</groupId>
                <artifactId>rocketmq-acl</artifactId>
                <version>4.9.8</version>
            </dependency>
            <dependency>
                <groupId>org.apache.rocketmq</groupId>
                <artifactId>rocketmq-common</artifactId>
                <version>4.9.8</version>
            </dependency>

            <!-- curator-framework -->
            <dependency>
                <groupId>org.apache.curator</groupId>
                <artifactId>curator-framework</artifactId>
                <version>5.8.0</version>
            </dependency>
            <dependency>
                <groupId>org.apache.curator</groupId>
                <artifactId>curator-recipes</artifactId>
                <version>5.8.0</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/io.github.java-diff-utils/java-diff-utils -->
            <dependency>
                <groupId>io.github.java-diff-utils</groupId>
                <artifactId>java-diff-utils</artifactId>
                <version>4.12</version>
            </dependency>

            <dependency>
                <groupId>jakarta.json</groupId>
                <artifactId>jakarta.json-api</artifactId>
                <version>2.0.1</version>
            </dependency>

            <dependency>
                <groupId>org.jetbrains</groupId>
                <artifactId>annotations</artifactId>
                <version>13.0</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/com.google.guava/guava -->
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>33.2.1-jre</version>
            </dependency>

            <dependency>
                <groupId>io.github.java-zengguang</groupId>
                <artifactId>litepress-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.java-zengguang</groupId>
                <artifactId>litepress-db</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.java-zengguang</groupId>
                <artifactId>litepress-web</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.java-zengguang</groupId>
                <artifactId>litepress-reaction</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.java-zengguang</groupId>
                <artifactId>litepress-router</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.java-zengguang</groupId>
                <artifactId>litepress-chain</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.java-zengguang</groupId>
                <artifactId>litepress-boot</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.java-zengguang</groupId>
                <artifactId>litepress-cache</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.java-zengguang</groupId>
                <artifactId>litepress-event</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>io.github.java-zengguang</groupId>
                <artifactId>litepress-network</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>org.nutz</groupId>
                <artifactId>ssdb4j</artifactId>
                <version>10.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>



        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.5.0</version>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                        <configuration>
                            <updatePomFile>true</updatePomFile>
                            <flattenMode>resolveCiFriendliesOnly</flattenMode>
                        </configuration>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
                <inherited>true</inherited>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
                <configuration>
                    <skipTests>true</skipTests>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.1.0</version>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
            <!-- 生成源码包 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>1.5</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.11.2</version>
                <configuration>
                    <source>${java.version}</source>
                    <doclint>none</doclint>
                    <show>protected</show>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <charset>UTF-8</charset>
                    <docencoding>UTF-8</docencoding>
                </configuration>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
                <version>0.8.0</version>
                <extensions>true</extensions>
                <configuration>
                    <publishingServerId>central</publishingServerId>
                </configuration>
            </plugin>

        </plugins>


        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
            <!--允许maven创建xml文件，否则xml要放在resources里-->
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.xml</include>
                </includes>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>


</project>