level=INFO
exception=strip: jdk.internal

writer1=console
writer1.format={thread} {context:threadID} {date: HH:mm:ss.SSS}{class}.{method}() {level}: {message}
writer1.exception=drop cause
writer2=rolling file
writer2.file=D:/logs/{date: yyyy-MM-dd}/log_{count}.txt
writer2.policies=startup, daily: 03:00
writer2.format={thread} {context:threadID}  {date: HH:mm:ss.SSS}{class}.{method}() {level}: {message}
writer2.exception=drop cause
