level=INFO
exception=strip: jdk.internal
writer1=console
writer1.format={thread} {context:traceId}  {date: HH:mm:ss.SSS}{class}.{method}() {level}: {message}
writer1.exception=drop cause

writer2=rolling file
writer2.file=/tomcat/webapp/logs/elk/{date: yyyy-MM-dd}/log_{count}.txt
writer2.policies=startup, daily: 03:00,size:100MB 
writer2.format={thread} {context:traceId}  {date: HH:mm:ss.SSS}{class}.{method}() {level}: {message}
writer2.exception=drop cause
writer2.backups=2




