<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.zg.litepress</groupId>
        <artifactId>litepress</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>chain</artifactId>


    <dependencies>
        <dependency>
            <groupId>com.zg.litepress</groupId>
            <artifactId>core</artifactId>
            <version>${revision}</version>
        </dependency>



        <!-- https://mvnrepository.com/artifact/com.google.guava/guava -->
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>33.2.1-jre</version>
        </dependency>
        <dependency>
            <groupId>com.zg.litepress</groupId>
            <artifactId>db</artifactId>
            <version>${revision}</version>

        </dependency>


    </dependencies>


</project>